### PR TITLE
[skip vbump] release v0.1.8

### PR DESCRIPTION
**Pull request by BFalquet**
[skip vbump]

release v0.1.8 

https://github.com/insightsengineering/dunlin/issues/166

thank you for the review

### CODE REVIEW

**Review by clarkliming — APPROVED** [review]
looks good, thank you

**Comment by clarkliming** [comment]
i will create a release in cran later

**Comment by BFalquet** [comment]
> i will create a release in cran later

Honestly, I think we don't need to do rush.

**Comment by clarkliming** [comment]
> > i will create a release in cran later
> 
> Honestly, I think we don't need to do rush.

after all the ticks in  https://github.com/insightsengineering/dunlin/issues/166 are finished

**Comment by clarkliming** [comment]
wait this is merge to main, and main bumped version?

**Pull request merged**
